### ISSUE TITLE
Proposal: access control system for statebus

### ISSUE THREAD

**Issue by gschorno** [invisible-college/statebus#12]
### Proposal: access control system for statebus

This is a simple solution for access control in statebus.
### Outline

On initialization, we have an access handler callback function

```
  allowAccess( verb, keypath, sessionid )
```

Verb is the operation in statebus 'get'|'put'|'delete', keypath is
the requested resource key path, and sessionid provides access to
current user info.

The callback is added to statebus:

```
  statebus.set( 'access', allowAccessFn )

  // or to use an ordered sequence of access handlers, something like:

  statebus.add( 'access', allowAccessFn )
```

allowAccess() uses the verb, key path, and sessionid to
calculate whether to grant access and returns:

```
  true            -- allow access
  false           -- deny access
  null/undefined  -- don't care, ask the next one
```

This allows multiple access handlers to be used, when null/undefined is 
returned the next access handler in the list is called. 

---

The initial use case for this is that I want to limit access to a particular key based 
on ip address (to begin with), with a callback this should be simple.

The advantage of this approach is that the access logic happens outside of
statebus, keeping the statebus core uncluttered.

Tried to keep this super simple, let me know what you think.

**Comment by toomim** [comment]
What do you think about simplifying this to:

```javascript
statebus.allow = function (key, method) {
    // return true if access should be given
    // else return false
}
```

We could use it for basic stuff like:
```javascript
statebus.allow = function (key, method) {
    if (is_private(key) && !current_user.is_admin)
        return false
    return true
}
```

More complex rules can be implemented by defining a custom `allow()` function:
```javascript
statebus.allow = rbac_security()  // Defined in some library of access control policies
statebus.allow.add('/admin', '*', 'admins')
statebus.allow.add('/profile/*', 'fetch')
statebus.allow.add('/profile/*', 'save',
    function (key, user) { return key.split()[3] === user.key.split()[2] }
)
```

**Comment by toomim** [comment]
Some observations are:
  - I think `sessionid` can be plugged into this outside statebus. Statebus might not need to know about sessions.
  - `keypath` is the same thing as `key` so I'm just calling it `key`
  - The logic for multiple handlers could be implemented outside of statebus core as well

**Comment by toomim** [comment]
Also, as I've said before, I'm really into this general idea.

It could be used for more than just security. You might set up an "allow" policy as a way to implement routing...

Actually... maybe this should be integrated with the route() function I implemented a few weeks ago:

```javascript
statebus.route = function (key, method) {
    // Calls all functions listening to this bus on key for method
}
```

It would work something like this:
```javascript
statebus.route = function (key, method) {
    for (each listener in listeners(key, method))
        if (this.allow(key, method))
            listener.call(this, key, method)
}
```

**Comment by toomim** [comment]
I've implemented something for multi-user access control. It's... a lot more complex. :/ I hope you don't hate me.

**Comment by toomim** [comment]
I think we could implement this simple API as a shortcut wrapper around it, though.

The new access control system creates a different view of the state space for every client. So for instance, each client can ```fetch("/current_user")``` and see something custom tailored to themselves. Or each client can ```fetch("/user_profile/bob")``` and see different amounts of information depending on their permissions.

So this not only gives you the ability to prevent people from seeing certain states, but also lets you define completely new states that only they can see, or arbitrarily transform states into versions consumable by them.

I implemented this by a hub-and-spoke of state spaces. There's a master space, and then each client has their own client space. These spaces are chained together with the statebus protocol. Requests first go to a client, and that client's `on_fetch()` handler can then choose to `fetch()` the data from the master space instead.

**Comment by toomim** [comment]
We've got pretty decent access control now: https://github.com/invisible-college/statebus/#programming-state-with-to_-handlers
